### ISSUE TITLE
[Feature Request] add custom shortcut  (since context menu would require addional permission) 

### ISSUE THREAD

**Issue by StavrosTsik** [igorlogius/save-tabs-to-bookmark-folder#4]
Please add mouse right-click support in contex menu to ditch the icon from toolbar!!

**Comment by igorlogius** [comment]
Generally that is no problem ... the only open question  is  in which contexts should the menu entries be displayed?  Since there are several.  (ref. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/ContextType) 

I guess starting with `all`  should be ok, even if that might suprise users to be presented with such an option when for example right clicking on a page link.

**Comment by igorlogius** [comment]
Well, damn i forgot that adding a context menu  will require to add the  `menus` permission. 
And i generally dont like  to change a permission set  ... since that kind of looks suspicious from a users perspective.

But i can see that some people would like to not use and see the toolbar button.

I could add a customizable Keyboard Shortcut which tiggers the save function 
that would not require to make any permission changes and you can trigger the save without having to interact and see  the toolbar button.  

@StavrosTsik 
Would that work for you?

**Comment by StavrosTsik** [comment]
That could work to (followed by an option in the configuration menu). But how difficult is, for the right click only implemented when the mouse is only on a tab and not for the whole system ? That also will require to add the menus permission ?

**Comment by igorlogius** [comment]
> But how difficult is, for the right click only implemented when the mouse is only on a tab and not for the whole system ? 

Its not difficult ... but as you already guessed even with the reduction to the tab scope context ...  it would still require the `menus` permission.  So that wouldn't make any difference. 

>  That could work

Ok, then i'll release an update of the addon where you can set a custom shortcut to trigger the save action and you can try if it works good enough. If not, just report back here and i'll see if we can find a different solution,  like making a fork of this addon with some modifications. -  I would have dont that from the start ... but i already had one discussion with the  AMO Reviewers ... because they thought 2 off my addons were "too similar" and wanted me to remove one or merge them.  Dont really wanna keep repeating that, if i can help it. 

Anyway ... i'll post an update here when the new version is out. 
Later.

**Comment by igorlogius** [comment]
Version 1.1.6 is out on AMO 
link: https://addons.mozilla.org/en-US/firefox/addon/save-tabs-to-bookmark-folder/

Default Shortcut is  "CTRL+ALT+S", but can be changed via. 
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox#firefox:win10:fx95

**Comment by igorlogius** [comment]
No Feedback in 15 days, guess i'll be closing this then for now.
